#Filtering Headlines dataset
avoid rerunning this notebook by checking in the drive folder for *filtered_headlines.csv*

###imports

In [ ]:
import pandas as pd

In [ ]:
# file dowloaded from: https://www.kaggle.com/datasets/thedevastator/women-in-headlines-bias?resource=download&select=headlines.csv
headlineframe = pd.read_csv('headlines.csv')

FileNotFoundError: ignored

##Cleaning the data

In [ ]:
headlineframe

,index,Unnamed: 0,url,headline_no_site,site,time,country,bias
0,0,0,https://www.iol.co.za/entertainment/movies-the...,'Lady Bird' buzzes through young sexuality,iol.co.za,2018-02-23 08:00:00+00:00,South Africa,0.000000
1,1,1,https://www.iol.co.za/entertainment/music/the-...,The shadowy urban POP super Starrah who loves ...,iol.co.za,2018-01-10 08:00:00+00:00,South Africa,0.166667
2,2,2,https://www.iol.co.za/entertainment/celebrity-...,Rihanna pens heartfelt tribute to her mom in b...,iol.co.za,2018-02-21 08:00:00+00:00,South Africa,0.333333
3,3,3,https://www.iol.co.za/news/south-africa/wester...,Shock as woman accused of killing teen girlfri...,iol.co.za,2018-02-27 08:00:00+00:00,South Africa,0.333333
4,4,4,https://www.iol.co.za/business-report/careers/...,TOP STORY: Meet South Africa's new first lady ...,iol.co.za,2018-02-15 08:00:00+00:00,South Africa,0.166667
...,...,...,...,...,...,...,...,...
382134,382134,382134,https://www.makeuseof.com/siri-no-longer-defau...,Siri Will No Longer Default to a Female Voice ...,makeuseof.com,2021-03-31 07:00:00+00:00,UK,0.166667
382135,382135,382135,https://www.cbn.co.za/featured/the-impact-of-c...,The impact of COVID 19 on women,cbn.co.za,2021-03-05 08:00:00+00:00,South Africa,0.166667
382136,382136,382136,https://www.cbn.co.za/featured/rand-air-commit...,Rand Air committed to excellence in safety wit...,cbn.co.za,2021-04-14 07:00:00+00:00,South Africa,0.166667
382137,382137,382137,https://www.cbn.co.za/featured/mother-citys-la...,Mother City's 'Lanseria': New airport in the p...,cbn.co.za,2021-03-10 08:00:00+00:00,South Africa,0.166667
382138,382138,382138,https://www.cbn.co.za/featured/zar-strength-co...,ZAR strength continues,cbn.co.za,2021-04-29 07:00:00+00:00,South Africa,0.000000

In [ ]:
# filter out the columns we want
headlines = headlineframe[['site', 'headline_no_site','time','country', 'bias']]

# drop NaNs
headlines = headlines.dropna()

In [ ]:
headlines

,site,headline_no_site,time,country,bias
0,iol.co.za,'Lady Bird' buzzes through young sexuality,2018-02-23 08:00:00+00:00,South Africa,0.000000
1,iol.co.za,The shadowy urban POP super Starrah who loves ...,2018-01-10 08:00:00+00:00,South Africa,0.166667
2,iol.co.za,Rihanna pens heartfelt tribute to her mom in b...,2018-02-21 08:00:00+00:00,South Africa,0.333333
3,iol.co.za,Shock as woman accused of killing teen girlfri...,2018-02-27 08:00:00+00:00,South Africa,0.333333
4,iol.co.za,TOP STORY: Meet South Africa's new first lady ...,2018-02-15 08:00:00+00:00,South Africa,0.166667
...,...,...,...,...,...
382134,makeuseof.com,Siri Will No Longer Default to a Female Voice ...,2021-03-31 07:00:00+00:00,UK,0.166667
382135,cbn.co.za,The impact of COVID 19 on women,2021-03-05 08:00:00+00:00,South Africa,0.166667
382136,cbn.co.za,Rand Air committed to excellence in safety wit...,2021-04-14 07:00:00+00:00,South Africa,0.166667
382137,cbn.co.za,Mother City's 'Lanseria': New airport in the p...,2021-03-10 08:00:00+00:00,South Africa,0.166667
382138,cbn.co.za,ZAR strength continues,2021-04-29 07:00:00+00:00,South Africa,0.000000

In [ ]:
# checking values
headlines['site'].unique()

In [ ]:
# working with a copy
copy = headlines.copy()

In [ ]:
copy

,site,headline_no_site,time,country,bias
0,iol.co.za,'Lady Bird' buzzes through young sexuality,2018-02-23 08:00:00+00:00,South Africa,0.000000
1,iol.co.za,The shadowy urban POP super Starrah who loves ...,2018-01-10 08:00:00+00:00,South Africa,0.166667
2,iol.co.za,Rihanna pens heartfelt tribute to her mom in b...,2018-02-21 08:00:00+00:00,South Africa,0.333333
3,iol.co.za,Shock as woman accused of killing teen girlfri...,2018-02-27 08:00:00+00:00,South Africa,0.333333
4,iol.co.za,TOP STORY: Meet South Africa's new first lady ...,2018-02-15 08:00:00+00:00,South Africa,0.166667
...,...,...,...,...,...
382134,makeuseof.com,Siri Will No Longer Default to a Female Voice ...,2021-03-31 07:00:00+00:00,UK,0.166667
382135,cbn.co.za,The impact of COVID 19 on women,2021-03-05 08:00:00+00:00,South Africa,0.166667
382136,cbn.co.za,Rand Air committed to excellence in safety wit...,2021-04-14 07:00:00+00:00,South Africa,0.166667
382137,cbn.co.za,Mother City's 'Lanseria': New airport in the p...,2021-03-10 08:00:00+00:00,South Africa,0.166667
382138,cbn.co.za,ZAR strength continues,2021-04-29 07:00:00+00:00,South Africa,0.000000

In [ ]:
# creating new columns 
copy['date'] = " "
copy['timezone'] = " "

# spliting the columns 
copy[['date', 'time']] = copy.time.str.split(" ", expand = True)
copy[['time', 'timezone']] = copy.time.str.split("+", expand = True)

# dropping unwanted info
copy = copy.drop(columns='timezone')

In [ ]:
# rounding just because
copy['bias'] = round(copy['bias'], 2)

In [ ]:
# renaming
copy = copy.rename(columns={'headline_no_site': 'headline'})

In [ ]:
copy

,site,headline,time,country,bias,date
0,iol.co.za,'Lady Bird' buzzes through young sexuality,08:00:00,South Africa,0.00,2018-02-23
1,iol.co.za,The shadowy urban POP super Starrah who loves ...,08:00:00,South Africa,0.17,2018-01-10
2,iol.co.za,Rihanna pens heartfelt tribute to her mom in b...,08:00:00,South Africa,0.33,2018-02-21
3,iol.co.za,Shock as woman accused of killing teen girlfri...,08:00:00,South Africa,0.33,2018-02-27
4,iol.co.za,TOP STORY: Meet South Africa's new first lady ...,08:00:00,South Africa,0.17,2018-02-15
...,...,...,...,...,...,...
382134,makeuseof.com,Siri Will No Longer Default to a Female Voice ...,07:00:00,UK,0.17,2021-03-31
382135,cbn.co.za,The impact of COVID 19 on women,08:00:00,South Africa,0.17,2021-03-05
382136,cbn.co.za,Rand Air committed to excellence in safety wit...,07:00:00,South Africa,0.17,2021-04-14
382137,cbn.co.za,Mother City's 'Lanseria': New airport in the p...,08:00:00,South Africa,0.17,2021-03-10
382138,cbn.co.za,ZAR strength continues,07:00:00,South Africa,0.00,2021-04-29

In [ ]:
# converting to datetime
copy['time'] = pd.to_datetime(copy['time'])
copy['date'] = pd.to_datetime(copy['date'])

In [ ]:
# reformatting
copy['date'] = copy['date'].dt.strftime("%m/%d/%Y")
copy['time'] = copy['time'].dt.strftime("%H:%M")

In [ ]:
copy

,site,headline,time,country,bias,date
0,iol.co.za,'Lady Bird' buzzes through young sexuality,08:00,South Africa,0.00,02/23/2018
1,iol.co.za,The shadowy urban POP super Starrah who loves ...,08:00,South Africa,0.17,01/10/2018
2,iol.co.za,Rihanna pens heartfelt tribute to her mom in b...,08:00,South Africa,0.33,02/21/2018
3,iol.co.za,Shock as woman accused of killing teen girlfri...,08:00,South Africa,0.33,02/27/2018
4,iol.co.za,TOP STORY: Meet South Africa's new first lady ...,08:00,South Africa,0.17,02/15/2018
...,...,...,...,...,...,...
382134,makeuseof.com,Siri Will No Longer Default to a Female Voice ...,07:00,UK,0.17,03/31/2021
382135,cbn.co.za,The impact of COVID 19 on women,08:00,South Africa,0.17,03/05/2021
382136,cbn.co.za,Rand Air committed to excellence in safety wit...,07:00,South Africa,0.17,04/14/2021
382137,cbn.co.za,Mother City's 'Lanseria': New airport in the p...,08:00,South Africa,0.17,03/10/2021
382138,cbn.co.za,ZAR strength continues,07:00,South Africa,0.00,04/29/2021

In [ ]:
# reorganizing
copy = copy[['date', 'time', 'headline','site','country', 'bias']]

In [ ]:
# making new columns for split
copy['s2'] = " "
copy['s3'] = " "

# getting the site title
copy[['site', 's2', 's3']] = copy.site.str.split(".", expand = True)

# dropping unwanted info
copy = copy.drop(columns=['s2', 's3'])

In [ ]:
copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 382139 entries, 0 to 382138
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   date      382139 non-null  object
 1   time      382139 non-null  object
 2   headline  382139 non-null  object
 3   site      382139 non-null  object
 4   country   382139 non-null  object
 5   bias      382139 non-null  float64
dtypes: float64(1), object(5)
memory usage: 28.5+ MB

In [ ]:
# converting back to datetime
copy['date'] = pd.to_datetime(copy['date'])

In [ ]:
copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 382139 entries, 0 to 382138
Data columns (total 6 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   date      382139 non-null  datetime64[ns]
 1   time      382139 non-null  object
 2   headline  382139 non-null  object
 3   site      382139 non-null  object
 4   country   382139 non-null  object
 5   bias      382139 non-null  float64
dtypes: datetime64[ns](1), float64(1), object(4)
memory usage: 28.5+ MB

In [ ]:
copy

,date,time,headline,site,country,bias
0,2018-02-23,08:00,'Lady Bird' buzzes through young sexuality,iol,South Africa,0.00
1,2018-01-10,08:00,The shadowy urban POP super Starrah who loves ...,iol,South Africa,0.17
2,2018-02-21,08:00,Rihanna pens heartfelt tribute to her mom in b...,iol,South Africa,0.33
3,2018-02-27,08:00,Shock as woman accused of killing teen girlfri...,iol,South Africa,0.33
4,2018-02-15,08:00,TOP STORY: Meet South Africa's new first lady ...,iol,South Africa,0.17
...,...,...,...,...,...,...
382134,2021-03-31,07:00,Siri Will No Longer Default to a Female Voice ...,makeuseof,UK,0.17
382135,2021-03-05,08:00,The impact of COVID 19 on women,cbn,South Africa,0.17
382136,2021-04-14,07:00,Rand Air committed to excellence in safety wit...,cbn,South Africa,0.17
382137,2021-03-10,08:00,Mother City's 'Lanseria': New airport in the p...,cbn,South Africa,0.17
382138,2021-04-29,07:00,ZAR strength continues,cbn,South Africa,0.00

In [ ]:
copy

,date,time,headline,site,country,bias
0,2018-02-23,08:00,'Lady Bird' buzzes through young sexuality,iol,South Africa,0.00
1,2018-01-10,08:00,The shadowy urban POP super Starrah who loves ...,iol,South Africa,0.17
2,2018-02-21,08:00,Rihanna pens heartfelt tribute to her mom in b...,iol,South Africa,0.33
3,2018-02-27,08:00,Shock as woman accused of killing teen girlfri...,iol,South Africa,0.33
4,2018-02-15,08:00,TOP STORY: Meet South Africa's new first lady ...,iol,South Africa,0.17
...,...,...,...,...,...,...
382134,2021-03-31,07:00,Siri Will No Longer Default to a Female Voice ...,makeuseof,UK,0.17
382135,2021-03-05,08:00,The impact of COVID 19 on women,cbn,South Africa,0.17
382136,2021-04-14,07:00,Rand Air committed to excellence in safety wit...,cbn,South Africa,0.17
382137,2021-03-10,08:00,Mother City's 'Lanseria': New airport in the p...,cbn,South Africa,0.17
382138,2021-04-29,07:00,ZAR strength continues,cbn,South Africa,0.00

##Save to cvs

In [ ]:
copy.to_csv('filtered_headlines.csv', index_label=False)